package com.seekerclaw.app.util

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.FileObserver
import android.util.Log
import androidx.core.content.ContextCompat
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import java.io.File

/**
 * Generic JSON-backed store for state shared between the main UI process
 * and the `:node` service process (BAT-512, BAT-511 family).
 *
 * Pre-CrossProcessStore, the app had two patterns layered uneasily:
 *
 *  - One-off file-IPC primitives ([ServiceState], [LogCollector], owner_ids,
 *    bridge_token, cron jobs). Cross-process-correct, but each one was
 *    hand-rolled; no reuse across new fields.
 *  - SharedPreferences. Per-process cached, BROKEN cross-process — every
 *    field that's read on BOTH UI and `:node` sides has the same staleness
 *    bug (BAT-509 caught it for provider/authType/model; MCP servers,
 *    search provider, agent name and credentials are all latent
 *    instances of the same bug).
 *
 * `CrossProcessStore<T>` consolidates the file-IPC pattern so the rest of
 * the BAT-511 family migrations (BAT-513, BAT-514, BAT-515, BAT-516) can
 * reuse one implementation instead of inventing a new file format each
 * time.
 *
 * ## Refresh strategy
 *
 * Two layered notification mechanisms:
 *
 *  1. **`FileObserver` (Node-side writes path).** When `:node` writes the
 *     file directly via `fs.writeFileSync`, the inotify event fires on
 *     the main UI process and triggers a [reload]. This is the BAT-518
 *     pattern: kernel-level event delivery, no polling.
 *
 *  2. **Package-scoped broadcast (Kotlin-side writes path).** When the
 *     writer is in the same package (any of our processes), [write]
 *     emits an [ACTION_STORE_CHANGED] broadcast carrying the
 *     [EXTRA_FILE_NAME] so other-process receivers can match by file
 *     name and reload. Faster than waiting for the file event in some
 *     edge cases (process boundary just after registration, races with
 *     restart windows).
 *
 * Either mechanism alone is sufficient — both layered gives belt-and-
 * suspenders reliability. Codex's review explicitly forbade the
 * 2s mtime polling fallback the original sketch proposed; FileObserver
 * is the reliable mechanism.
 *
 * ## Atomicity
 *
 * Writes go through a `<filename>.tmp` then `renameTo(filename)`. The
 * rename is atomic on every Android-supported filesystem (ext4, F2FS),
 * so a reader can never observe a half-written file. No fsync —
 * Android-style mobile usage doesn't justify the latency cost; if the
 * device powers off mid-write, the worst case is the previous good
 * version stays on disk.
 *
 * ## What this class does NOT do
 *
 *  - Does not migrate any existing field. New code only — sibling
 *    tickets do migrations one field at a time (BAT-513 onward).
 *  - Does not provide encryption. Sensitive fields (API keys, OAuth
 *    tokens) stay in [com.seekerclaw.app.config.KeystoreHelper] /
 *    SharedPreferences for now. BAT-516 will revisit and add a
 *    Keystore-backed encryption layer.
 *  - Does not deprecate [ServiceState] or [LogCollector] — those are
 *    the prior-art that informed this abstraction; they keep their
 *    bespoke implementations for now (they've shipped and are stable).
 *
 * @param T type of the persisted value. Must be `@Serializable`-able
 *          via the supplied [serializer].
 * @param context any [Context] (process-scoped). Used for `filesDir`,
 *                broadcast send/register, and FileObserver attach.
 * @param fileName basename of the JSON file relative to `filesDir`,
 *                 e.g. `"runtime_state.json"`. Avoid path separators —
 *                 only direct children of `filesDir` are supported.
 * @param serializer kotlinx.serialization serializer for [T]. Pass
 *                   `MyType.serializer()` (generated by `@Serializable`)
 *                   or `serializer<MyType>()`.
 * @param initial value to return from [read] / [state] when the file
 *                doesn't exist or fails to parse.
 * @param coroutineScope scope used to dispatch reload work off the
 *                       FileObserver / receiver threads. Defaults to
 *                       `Dispatchers.IO`.
 */
class CrossProcessStore<T>(
    private val context: Context,
    private val fileName: String,
    private val serializer: KSerializer<T>,
    private val initial: T,
    private val coroutineScope: CoroutineScope = CoroutineScope(Dispatchers.IO),
) {
    init {
        // BAT-512 (Copilot review fix): fileName is documented as a
        // basename relative to filesDir. Without enforcement, a caller
        // passing "../etc/passwd" or "subdir/file.json" would resolve
        // OUTSIDE filesDir — path traversal. Validate up-front so
        // misuse is caught at construction, not at first write.
        require(fileName.isNotBlank()) { "fileName must not be blank" }
        require(fileName == File(fileName).name) {
            "fileName must be a basename (no path separators), got: '$fileName'"
        }
        require(!fileName.contains("..")) {
            "fileName must not contain '..' (path traversal), got: '$fileName'"
        }
    }

    private val file: File = File(context.filesDir, fileName)
    private val tmpFile: File = File(context.filesDir, "$fileName.tmp")
    private val writeLock = Any()
    private val _state = MutableStateFlow(initial)

    /** Observable state. Emits new values on every successful write or reload. */
    val state: StateFlow<T> = _state.asStateFlow()

    private val json = Json {
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    private var fileObserver: FileObserver? = null
    private var receiver: BroadcastReceiver? = null

    init {
        // Synchronous catch-up read: if the file already exists from a
        // prior process, hydrate _state immediately so the first
        // `state.value` access returns the persisted value, not
        // `initial`.
        _state.value = read()
        startWatching()
    }

    /**
     * Synchronously parse the JSON file and return the value. Idempotent
     * and side-effect-free. Returns [initial] on missing file or
     * malformed JSON (logged at WARN — never throws).
     */
    fun read(): T {
        if (!file.exists()) return initial
        return try {
            json.decodeFromString(serializer, file.readText())
        } catch (e: Exception) {
            Log.w(TAG, "[$fileName] decode failed, returning initial: ${e.message}")
            initial
        }
    }

    /**
     * Persist [value] atomically and notify both same-process observers
     * (via [state]) and other-process observers (via FileObserver +
     * broadcast).
     *
     * Concurrent writes from the same process serialize via [writeLock]
     * — `writeText` + `renameTo` is a critical section. Cross-process
     * concurrent writes are last-writer-wins (filesystem rename
     * semantics); callers that need stronger ordering must coordinate
     * separately.
     */
    fun write(value: T) {
        synchronized(writeLock) {
            try {
                val text = json.encodeToString(serializer, value)
                tmpFile.writeText(text)
                // BAT-512 (Copilot review fix): use NIO `Files.move`
                // with REPLACE_EXISTING + ATOMIC_MOVE so the rename is
                // atomic AT THE FILESYSTEM LEVEL even when the
                // destination already exists. The earlier delete +
                // renameTo fallback opened a window in which
                // FileObserver fired DELETE, the corresponding reload
                // landed `initial` in `_state`, and only the
                // subsequent CREATE/MOVED_TO restored the correct
                // value — observers briefly saw garbage.
                //
                // ATOMIC_MOVE + REPLACE_EXISTING is supported on the
                // filesystems Android uses (ext4, F2FS). Min SDK 34 so
                // java.nio.file is available. AtomicMoveNotSupported
                // can occur on cross-device moves only, which doesn't
                // happen here (both files are under filesDir on the
                // same partition); we still degrade gracefully if it
                // does.
                try {
                    java.nio.file.Files.move(
                        tmpFile.toPath(),
                        file.toPath(),
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                        java.nio.file.StandardCopyOption.ATOMIC_MOVE,
                    )
                } catch (_: java.nio.file.AtomicMoveNotSupportedException) {
                    // Fall back to non-atomic REPLACE_EXISTING — still
                    // single-syscall (no DELETE event), just not
                    // strictly atomic if the kernel decides otherwise.
                    java.nio.file.Files.move(
                        tmpFile.toPath(),
                        file.toPath(),
                        java.nio.file.StandardCopyOption.REPLACE_EXISTING,
                    )
                }
                _state.value = value
                broadcastChanged()
            } catch (e: Exception) {
                Log.e(TAG, "[$fileName] write failed: ${e.message}", e)
            } finally {
                // Defensive: clean up a leftover .tmp on the failure path
                // so we don't accumulate cruft. No-op when the move
                // succeeded (the source inode is gone).
                if (tmpFile.exists()) tmpFile.delete()
            }
        }
    }

    /**
     * Re-read the file from disk and update [state]. Called from the
     * FileObserver and broadcast receiver — public so tests and
     * pull-style consumers can force a refresh.
     */
    fun reload() {
        val current = read()
        _state.value = current
    }

    private fun broadcastChanged() {
        try {
            val intent = Intent(ACTION_STORE_CHANGED)
                .setPackage(context.packageName)
                .putExtra(EXTRA_FILE_NAME, fileName)
            context.sendBroadcast(intent)
        } catch (e: Exception) {
            // Broadcast failure is non-fatal — FileObserver in the other
            // process will still pick up the file change.
            Log.w(TAG, "[$fileName] broadcast failed: ${e.message}")
        }
    }

    private fun startWatching() {
        attachFileObserver()
        registerBroadcastReceiver()
    }

    private fun attachFileObserver() {
        val parent = file.parentFile ?: run {
            Log.w(TAG, "[$fileName] no parent dir; FileObserver skipped")
            return
        }
        // Same FileObserver pattern LogCollector / ServiceState use post-
        // BAT-518: watch the parent dir, filter by basename in onEvent.
        // Mask covers every way the file can change in this codebase
        // (writeText, atomic .tmp+rename, delete, first-time create).
        fileObserver = object : FileObserver(
            parent,
            FileObserver.MODIFY or FileObserver.CLOSE_WRITE or
                FileObserver.MOVED_TO or FileObserver.CREATE or
                FileObserver.DELETE,
        ) {
            override fun onEvent(event: Int, path: String?) {
                // path is the basename for file-level events, null for
                // directory-level events (also the only signal we get
                // for inotify queue overflow). Reload on either.
                val basename = path?.substringAfterLast('/')
                if (basename == null || basename == fileName) {
                    coroutineScope.launch { reload() }
                }
            }
        }.also { it.startWatching() }
    }

    private fun registerBroadcastReceiver() {
        val r = object : BroadcastReceiver() {
            override fun onReceive(ctx: Context, intent: Intent) {
                if (intent.action != ACTION_STORE_CHANGED) return
                val name = intent.getStringExtra(EXTRA_FILE_NAME)
                if (name == fileName) {
                    coroutineScope.launch { reload() }
                }
            }
        }
        ContextCompat.registerReceiver(
            context,
            r,
            IntentFilter(ACTION_STORE_CHANGED),
            ContextCompat.RECEIVER_NOT_EXPORTED,
        )
        receiver = r
    }

    /**
     * Release the FileObserver and broadcast receiver. Production
     * stores live for the process lifetime — calling [close] is only
     * meaningful for tests or hot-swap scenarios. Idempotent.
     */
    fun close() {
        fileObserver?.stopWatching()
        fileObserver = null
        receiver?.let {
            try {
                context.unregisterReceiver(it)
            } catch (_: Exception) {
                // Already unregistered, or never registered (test paths).
            }
        }
        receiver = null
    }

    companion object {
        private const val TAG = "CrossProcessStore"

        /**
         * Package-scoped broadcast action used as the fast path for
         * Kotlin-side cross-process notification. Receivers must filter
         * on [EXTRA_FILE_NAME] so a single-store reload doesn't trigger
         * unrelated stores.
         */
        const val ACTION_STORE_CHANGED = "com.seekerclaw.app.action.CROSS_PROCESS_STORE_CHANGED"

        /** Intent extra carrying the basename of the changed store file. */
        const val EXTRA_FILE_NAME = "fileName"
    }
}
